#!groovy​


//final NEXUS_REPO = 'alm-demo'
node('maven') {
    stage('Build') {
        checkout scm
        def pom = readMavenPom file: 'pom.xml'
        sh "mvn -B versions:set -DnewVersion=${pom.version}-${BUILD_NUMBER}"
        sh "mvn -B -Dmaven.test.skip=true clean package"
        stash name: "artifact", includes: "target/soccer-stats-*.jar"
    }

    stage('Unit Tests') {   
        sh "mvn -B test"
        stash name: "unit_tests", includes: "target/surefire-reports/**"
    }

    stage('Integration Tests') {
        sh "mvn -B verify -Dsurefire.skip=true"
        stash name: 'it_tests', includes: 'target/failsafe-reports/**'
    }

    stage('Static Analysis') {
        withSonarQubeEnv('sonar'){
            unstash 'it_tests'
            unstash 'unit_tests'
            sh 'mvn sonar:sonar -DskipTests'
        }
    }
/*
    stage('Artifact Upload') {
        unstash 'artifact'

        def pom = readMavenPom file: 'pom.xml'
        def file = "${pom.artifactId}-${pom.version}"
        def jar = "target/${file}.jar"

        sh "cp pom.xml ${file}.pom"
        sh "mvn -B -Popenshift clean deploy -Dmaven.test.skip=true"

*/
    /*
        nexusArtifactUploader artifacts: [
                [artifactId: "${pom.artifactId}", classifier: '', file: "target/${file}.jar", type: 'jar'],
                [artifactId: "${pom.artifactId}", classifier: '', file: "${file}.pom", type: 'pom']
            ], 
            credentialsId: 'nexus', 
            groupId: "${pom.groupId}", 
            nexusUrl: NEXUS_URL, 
            nexusVersion: 'nexus3', 
            protocol: 'http', 
            repository: NEXUS_REPO, 
            version: "${pom.version}"        
            */
  //  }

    stage('Build Image') {
        unstash name:"artifact"
        def pom = readMavenPom file: "pom.xml"
        def repoPath =  "${pom.groupId}".replace(".", "/") + 
                        "/${pom.artifactId}"

        def version = pom.version
        sh "oc start-build soccer-stats --from-file=target/${pom.artifactId}-${version}.jar --follow"
    }
}

stage('Deploy') {
    node {
        openshiftDeploy depCfg: 'soccer-stats'
        openshiftVerifyDeployment depCfg: 'soccer-stats', replicaCount: 1, verifyReplicaCount: true
    }
}